// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvyjbvaxxsgifbugfwbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2eWpidmF4eHNnaWZidWdmd2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDgwNzksImV4cCI6MjA3Njk4NDA3OX0.tkqgo6DiEr9lzXUH8vhrf4ZXGWW4k6pLqzJJyZBX2AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});